@hostname = localhost

@port = 3000

@host = {{hostname}}:{{port}}

@protocol = http://

@url = {{protocol}}{{host}}

@contentType = application/json

@userToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTMwOWE5MTY0MDI5OTNjYzA1MWQ5MzUiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjMwNTc1MjQ5fQ.fAkq0HrxV7k3XGUunK4uVY4vdhM8yaK7AO6m25FdiY0

@adminToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MTMwOWE1MzY0MDI5OTNjYzA1MWQ5MzIiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2MzA1NzUxODd9.m2d2g2tLzKw39B5Upb1TfZxCg3N5cRfAzx0ZSvskIj0

### Add an user
POST {{url}}/api/users
Content-Type: {{contentType}}

{
  "name": "sohan",
  "email": "sohan@ndub.edu.bd",
  "password": "sohaN123",
  "isAdmin": true
}
###
POST {{url}}/api/users
Content-Type: {{contentType}}

{
  "name": "ricky",
  "email": "ricky@ndub.edu.bd",
  "password": "sohaN123"
}


### Get all Users

GET {{url}}/api/users
x-auth-token: {{adminToken}}


### Get profile of the user after login

GET {{url}}/api/users/me
x-auth-token: {{adminToken}}
###
GET {{url}}/api/users/me
x-auth-token: {{userToken}}


### Get a single user by id
GET {{url}}/api/users/612f4afc18461806848cd6fc
x-auth-token: {{adminToken}}
###
GET {{url}}/api/users/612f4afc18461806848cd6fc
x-auth-token: {{userToken}}